### ISSUE TITLE
unwanted popup appearing when moving out of an entity

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1250]
Issue discussed with @SyamBabu-M and team.
See this entity (Amuzart organization) in the cms: https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/6451675ce19f7200646d24c8 - created by atoutculture

Steps to reproduce:
1. go into the edit page for Amuzart
2. Exit (go back).
3. This popup appears (when no changes has been made)

![Image](https://github.com/user-attachments/assets/8185d6a7-1eec-4cf4-ba8d-65bd55748423)

Likely cause is a lack of html tag (P-tag) in the Description. Please cover this issue for all entities.

**Comment by AbhishekPAnil** [comment]
Bug report :
The description doesn't have tags .The editor is trying to add tags since its missing.Hence the change occurs and thus the pop up
```
"description": {
        "en": "Amuzart's mission is to allow the exploration of artistic practices of visual and decorative arts in a playful, educational, humanistic and open-minded spirit. The apprentice artists, young and old, will live an experience of awakening to the visual arts, educational and fun. One of our objectives is to equip children or adults to develop their creativity and self-confidence. We adopt a caring educational approach.",
        "fr": "La mission d'Amuzart est de permettre l'exploration des pratiques artistiques des arts visuels et des arts décoratifs dans un esprit ludique, éducatif, humaniste et ouvert sur le monde. Les apprentis artistes, petits et grands, vivront une expérience d'éveil aux arts plastiques, éducative et amusante. L'un des objectifs est aussi d'outiller les enfants ou les adultes afin que l'artiste apprenant développe sa créativité et sa confiance en soi. Nous adoptons une approche éducative bienveillante.<br><br>L'un des objectifs est aussi d'outiller les enfants ou les adultes afin que l'artiste apprenant développe sa créativité et sa confiance en soi. <br><br>Nous adoptons une approche éducative bienveillante. "
    },
```

**Comment by SyamBabu-M** [comment]
@troughc I had done a fix for this issue during the development of https://github.com/culturecreates/footlight-calendar-api/issues/1001 
but that feature hasn't been completed yet.

Also, the fix that I implemented is tightly coupled with the work being done in #1001 and this fix will not work for the current CMS.  If we choose to address this issue separately, additional effort will be required to make the solution compatible with the current system.
So considering that should we address this separately? Or is it ok to fix this along with #1001?

**Comment by troughc** [comment]
@SyamBabu-M Please fix this along with https://github.com/culturecreates/footlight-calendar-api/issues/1001 
you do NOT need to address separately. 

Should we keep this issue open so we can check when we implement https://github.com/culturecreates/footlight-calendar-api/issues/1001 ?

If you think we do not need this issue to be open, please close it and add a test for this popup in the other issue. 

either way works for me.

**Comment by SyamBabu-M** [comment]
We can keep this open. I ll add a close tag for this issue in the PR for https://github.com/culturecreates/footlight-calendar-api/issues/1001

**Comment by troughc** [comment]
This looks good now. PASSED
Close when you are ready @SyamBabu-M

**Comment by troughc** [comment]
@SyamBabu-M I just tested this in production and staging and the unwanted popup is still appearing for Amuzart. The popup appears even when i don't change anything (see description and URL link at the top).
Please take a look.

**Comment by troughc** [comment]
This issue is hard to fix. Known issue to discuss with @sahahali (we can see cause in comment by Abhishek above).

**Comment by troughc** [comment]
Bug report :
The description doesn't have tags .The editor is trying to add

tags since its missing.Hence the change occurs and thus the pop up

"description": {
        "en": "Amuzart's mission is to allow the exploration of artistic practices of visual and decorative arts in a playful, educational, humanistic and open-minded spirit. The apprentice artists, young and old, will live an experience of awakening to the visual arts, educational and fun. One of our objectives is to equip children or adults to develop their creativity and self-confidence. We adopt a caring educational approach.",
        "fr": "La mission d'Amuzart est de permettre l'exploration des pratiques artistiques des arts visuels et des arts décoratifs dans un esprit ludique, éducatif, humaniste et ouvert sur le monde. Les apprentis artistes, petits et grands, vivront une expérience d'éveil aux arts plastiques, éducative et amusante. L'un des objectifs est aussi d'outiller les enfants ou les adultes afin que l'artiste apprenant développe sa créativité et sa confiance en soi. Nous adoptons une approche éducative bienveillante.<br><br>L'un des objectifs est aussi d'outiller les enfants ou les adultes afin que l'artiste apprenant développe sa créativité et sa confiance en soi. <br><br>Nous adoptons une approche éducative bienveillante. "
    },
This is not just happening for amuzart.There are other entities like this.
Eg :
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/add-organization?id=6629f51c0796c3006456e728 - created by asalle odyssée
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/add-organization?id=6451675fe19f7200646d2546 - created by atoutculture

NOT WORKING CAITLIN THINKS:
Below entity has a correct representation of description :
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/add-organization?id=64556239127fe0006438e773 - created by atoutculture

@sahalali will look into how to solve this.

**Comment by troughc** [comment]
@AbhishekPAnil is this the correct test? 
I checked the orgs and places mentioned previously by me, and the popup didn't appear when I exited an edit form without doing anything.  PASSED
