### ISSUE TITLE
Warning to save appears even when I haven't changed anything

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#253]
When I click event list to exit an event that I haven't changed, the following warning appears:
You have unsaved changes. Are you sure you want to discard them?

Preferred behavour: if no changes have been made to an event, the user is not asked if they want to save your changes. For exmaple event see http://staging.cms.footlight.io/dashboard/62df90a4820e41f7c1359760/events/add-event/642282e8af15d1006484db82

**Comment by troughc** [comment]
@saumier can you also look at this issue.

**Comment by saumier** [comment]
@troughc Please prioritize. In my opinion it is low priority, and should only be done after clients are live.

**Comment by troughc** [comment]
@saumier this issue has also been raised by Signe Laval in support ticket #24
I am prioritizing that one.

**Comment by saumier** [comment]
@troughc You already linked it by adding the link in your comment above. So I am closing this as duplicate.

**Comment by troughc** [comment]
@saumier I am reopening because actually it is not exactly a dupicate (sorry, my mistake). This one is about not making any changes and just exiting the issue. Then an error appears. 
I tested this today by going into an existing event and not doing anything

I still get a message even though I didn't change anything. So this is not fixed.


![Image](https://github.com/culturecreates/tech-support-tickets/assets/64489312/3f474bbd-1165-407a-9223-1772be27e3d4)

**Comment by AbhishekPAnil** [comment]
@troughc  Can we discuss this after the stand up.I am unable to reproduce the issue in staging for the same event.

**Comment by troughc** [comment]
No longer able to reproduce this after doing a hard cache reload which was needed after Abhiskek implemented the fix.
Tested: PASSED

**Comment by troughc** [comment]
@AbhishekPAnil One thing I noticed is that the creator of the last two events that I saw this issue happen with was salayer - this may be a red herring, but just in case, I thought I'd mention it.

**Comment by troughc** [comment]
@AbhishekPAnil this issue just occurred with another user in Tout Culture (one of the aggregators): https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6495a8f195ffd60064aa92db

**Comment by troughc** [comment]
Here is one: Here is one: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64af648a3c19fa0064e777cf

**Comment by troughc** [comment]
Here is one in production: https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64af64603c19fa0064e77213
I find them by looking in events added by the aggregator that have not been updated by anyone. :)

**Comment by AbhishekPAnil** [comment]
An event to test in staging:
https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/6495d08895ffd60064aaef38

**Comment by troughc** [comment]
@AbhishekPAnil please see my comment in https://github.com/culturecreates/footlight-calendar-api/issues/411
I closed that issue but I am getting this kind of error for my tests. 
Steps to reproduce:
1. create an event that you want to publish (or if you are logged in as a guest - send to review). 
2. fill in all required fields and click publish/send to review
3.  the error message asking me about unsaved changes appears. If i cancel, I go stay in the event details, and a popup message tells me that it saved successfully. 
4. Try to exit by clicking Events - the first message appears again (
5. First alternative: Try to exit by clicking OK in the popup. You exit and then see that the event did save successfully (as noted in step 4).
6. Second Alternative: try to exit by clicking Send to review again - nothing happens. Then try to click events - you exit to the calendar view and see that the event saved successfully.

**Comment by AbhishekPAnil** [comment]
Two causes were found during debugging:
1.Empty spaces at the end were removed by quill editor .
2.Empty paragraphs or<br>were also removed by quill editor .

The first bug is fixed and updated in staging.

**Comment by AbhishekPAnil** [comment]
As per previous discussion,
@AbhishekPAnil will try to remove the empty paragraphs or spacing at the end of the description to resolve the second issue mention in the previous comment

**Comment by AbhishekPAnil** [comment]
@troughc I have updated staging with the suggested implementation .Please test it with different events.Try to add empty paragraphs inside the description(french or english) field to test out the use case.

**Comment by troughc** [comment]
@AbhishekPAnil I am still getting the error message when I add empty paragraphs to the end of descriptions in existing events (published). I did this in Tout Culture, the first 4 existing events. After adding extra paragraphs, everytime I clicked Save for each published event, the screenshot-ed error appeared.

Also, I created this event as draft: https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/65b13e7b8252ed00a6ca9e97
I added extra paragraphs to the description and the error appeared.

**Expected behavior:** No error message will be displayed for this scenario. Instead the success message is displayed as the event successfully saves and the extra paragraphs are removed. 

![Image](https://github.com/culturecreates/footlight-app/assets/64489312/97aa80f1-fae1-4330-a2db-37468e85ac95)

**Comment by AbhishekPAnil** [comment]
@troughc the pop up came after  refreshing the page also?

**Comment by troughc** [comment]
@AbhishekPAnil yes, it is. I just retested it on chrome. I did a hard cache reload, I logged out and logged back in and then added paragraph returns to a description in a published event. When I click Save, I get the error message.

**Comment by AbhishekPAnil** [comment]
@troughc I have done one more fix regarding this issue and updated in staging.Please test it out and let me know if anymore changes are required.Thanks!

**Comment by AbhishekPAnil** [comment]
Since the error was happening for saved events I was mainly focused on solving the issue for saved events.The above issue you mentioned was unhandled and thanks for noticing it.The issue is now fixed and updated in staging.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
