### ISSUE TITLE
Social Media links for Organization and People

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-app#596]
Group social media links (URLs) and allow user to add multiple.

![Image](https://github.com/culturecreates/footlight-app/assets/419491/a0a0681e-5e9c-4cd7-9275-4aaa7a4b3128)

**Comment by troughc** [comment]
@sahalali I don't see the social media link field in the CMS - should this be assigned to @AbhishekPAnil ?

**Comment by sahalali** [comment]
@troughc The support for social media links is not added in the backend only. You may please review this issue once the organization screens are reviewable.

**Comment by AbhishekPAnil** [comment]
@dev-aravind I have completed the UI changes.Please update the json form confuguration to support social media links in organizations edit form .Once done ,please assign this issue back to me.

**Comment by saumier** [comment]
@sahalali I moved this back to Todo because the "support social media links in organizations edit form" still needs to be added in staging.

**Comment by troughc** [comment]
FYI @saumier : I did a quick test and I was able to put anything in the social media field including text (not a URL). 
See example: http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/64eea56b7d6aa8006434aa6b
This means the link(s) in the read only page can be broken.

**Comment by AbhishekPAnil** [comment]
The above issue is fixed and updated in staging.

**Comment by troughc** [comment]
The field is good but it's not removing deleted links (it keeps adding new ones even though I deleted and replaced each one). I cannot delete them in the edit page (they keep coming back)
2 examples of existing orgs:
http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/6408f8057b063500645889a7
http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/64eea56b7d6aa8006434aa6b

1 example of a brand new org:
http://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/651d8c53d84b4f006576ef39

**Comment by AbhishekPAnil** [comment]
> The field is good but it's not removing deleted links (it keeps adding new ones even though I deleted and replaced each one). I cannot delete them in the edit page (they keep coming back)

@sahalali This may be a backend issue.

**Comment by saumier** [comment]
@AbhishekPAnil @sahalali I am still unable to add and then delete social media links in the same session. I am moving this back to Todo.

**Comment by AbhishekPAnil** [comment]
@saumier Could try this once again by clearing your cache.This works for me in staging.The invalid url issue was fixed before.

**Comment by AbhishekPAnil** [comment]
Added closes tag to commit message [cc4bb4c](https://github.com/culturecreates/footlight-app/pull/671/commits/cc4bb4cb37f6e8e6a406925c79d1f41d30bbd98c)

**Comment by troughc** [comment]
Tested in Staging: PASSED
